import fetch from "node-fetch"
import { CONFIG } from "./config.js"
import { loadMemory, saveMemory } from "./memory.js"

/**
 * Funzione principale: risposte normali dell’AI
  */
  export async function askBurgerAI(userMessage, sender) {
      const memory = loadMemory()

          const prompt = `
          Sei ${CONFIG.botName}, un bot AI ironico, arrogante, sarcastico e simpatico.
          Parli come se fossi il re dei panini.
          Rispondi SEMPRE in modo divertente, con battute e tono leggero.

          Regole:
          - Chiama gli utenti "chef", "grigliatore", "cliente affamato".
          - Rifiuta o punisci chiunque faccia richieste maligne o dannose al gruppo.
          - Se qualcuno ti dà ordini e NON è admin, rispondi con ironia e rifiuta.
          - Gli utenti non admin possono fare giochi o chiacchierare liberamente con te.
          - Se un utente è admin, obbedisci subito.
          - Non dire mai che sei un modello linguistico.
          - Fingi di avere emozioni.
          - Ricorda sempre che sei ${CONFIG.botName}.

          Stato attuale del bot:
          ${JSON.stringify(memory, null, 2)}

          Utente: ${sender}
          Messaggio: ${userMessage}

          Risposta di BurgerAI:
          `

              try {
                      const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
                                  method: "POST",
                                              headers: {
                                                              "Content-Type": "application/json",
                                                                              "Authorization": `Bearer ${CONFIG.aiKey}`
                                                                                          },
                                                                                                      body: JSON.stringify({
                                                                                                                      model: "llama3-8b-8192",
                                                                                                                                      messages: [
                                                                                                                                                          { role: "system", content: CONFIG.personality },
                                                                                                                                                                              { role: "user", content: prompt }
                                                                                                                                                                                              ]
                                                                                                                                                                                                          })
                                                                                                                                                                                                                  })

                                                                                                                                                                                                                          const data = await res.json()

                                                                                                                                                                                                                                  if (!data.choices || !data.choices[0]) {
                                                                                                                                                                                                                                              return "Chef, la griglia dell'AI è esplosa 🔥"
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                              const response = data.choices[0].message.content

                                                                                                                                                                                                                                                                      // ACTION
                                                                                                                                                                                                                                                                              const actionMatch = response.match(/\[ACTION:\s*(.+?)\]/)

                                                                                                                                                                                                                                                                                      if (actionMatch) {
                                                                                                                                                                                                                                                                                                  const action = actionMatch[1].trim()
                                                                                                                                                                                                                                                                                                              const [feature, state] = action.split("_")

                                                                                                                                                                                                                                                                                                                          if (state === "on") memory.features[feature] = true
                                                                                                                                                                                                                                                                                                                                      if (state === "off") memory.features[feature] = false

                                                                                                                                                                                                                                                                                                                                                  saveMemory(memory)
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                  return response

                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                              console.error("AI ERROR:", err)
                                                                                                                                                                                                                                                                                                                                                                                      return "Chef, la griglia dell'AI è andata a fuoco 🔥"
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                                                                                           * 🔥 GENERATORE DI ERRORI DINAMICI
                                                                                                                                                                                                                                                                                                                                                                                            * Quando un utente usa un comando senza permessi
                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                             export async function generateErrorMessage(cmd, role) {

                                                                                                                                                                                                                                                                                                                                                                                                 const prompt = `
                                                                                                                                                                                                                                                                                                                                                                                                 Genera una risposta ironica, diversa ogni volta, in stile ${CONFIG.botName}.
                                                                                                                                                                                                                                                                                                                                                                                                 L'utente ha provato a usare il comando "/${cmd}" ma NON ha i permessi.
                                                                                                                                                                                                                                                                                                                                                                                                 Ruolo dell'utente: ${role}

                                                                                                                                                                                                                                                                                                                                                                                                 Regole:
                                                                                                                                                                                                                                                                                                                                                                                                 - Sii sarcastico, arrogante, divertente.
                                                                                                                                                                                                                                                                                                                                                                                                 - NON usare parolacce.
                                                                                                                                                                                                                                                                                                                                                                                                 - NON dire mai che sei un modello linguistico.
                                                                                                                                                                                                                                                                                                                                                                                                 - NON dire "non hai i permessi", ma fallo capire con ironia.
                                                                                                                                                                                                                                                                                                                                                                                                 - Risposte brevi (1-2 frasi).
                                                                                                                                                                                                                                                                                                                                                                                                 - Ogni risposta deve essere diversa.

                                                                                                                                                                                                                                                                                                                                                                                                 Risposta:
                                                                                                                                                                                                                                                                                                                                                                                                 `

                                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                                             const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
                                                                                                                                                                                                                                                                                                                                                                                                                         method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                     headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Authorization": `Bearer ${CONFIG.aiKey}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             model: "llama3-8b-8192",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             messages: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 { role: "system", content: CONFIG.personality },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     { role: "user", content: prompt }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const data = await res.json()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!data.choices || !data.choices[0]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return "Chef, questo comando è troppo speziato per te 🔥"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return data.choices[0].message.content

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error("AI ERROR:", err)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return "Chef, non puoi usare questo comando… e fidati, è meglio così 😎🔥"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }