import makeWASocket, {
        DisconnectReason,
            useMultiFileAuthState
            } from "@whiskeysockets/baileys"

            import { Boom } from "@hapi/boom"
            import { loadMemory, saveMemory, getRole, setCapo } from "./memory.js"
            import { handleCommand } from "./commands.js"
            import { askBurgerAI } from "./ai.js"
            import { isAdmin, isOwner, reply, log } from "./utils.js"

            async function startBot() {
                const { state, saveCreds } = await useMultiFileAuthState("./session")

                    const sock = makeWASocket({
                            auth: state,
                                    printQRInTerminal: true,
                                    browser: ["Chrome (Linux)", "Chrome", "1.0"]
                                        })

                                            sock.ev.on("creds.update", saveCreds)

                                                // 🔥 RICONNESSIONE AUTOMATICA
                                                    sock.ev.on("connection.update", (update) => {
                                                            const { connection, lastDisconnect } = update
                                                                    if (connection === "close") {
                                                                                const shouldReconnect =
                                                                                                lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut
                                                                                                            if (shouldReconnect) startBot()
                                                                                                                    }
                                                                                                                        })

                                                                                                                            // 🔥 GESTIONE MESSAGGI
                                                                                                                                sock.ev.on("messages.upsert", async ({ messages }) => {
                                                                                                                                        try {
                                                                                                                                                    const msg = messages[0]
                                                                                                                                                                if (!msg.message) return

                                                                                                                                                                            const from = msg.key.remoteJid
                                                                                                                                                                                        const isGroup = from.endsWith("@g.us")
                                                                                                                                                                                                    const sender = msg.key.participant || msg.key.remoteJid
                                                                                                                                                                                                                const body =
                                                                                                                                                                                                                                msg.message.conversation ||
                                                                                                                                                                                                                                                msg.message.extendedTextMessage?.text ||
                                                                                                                                                                                                                                                                ""

                                                                                                                                                                                                                                                                            log("info", `Messaggio da ${sender}: ${body}`)

                                                                                                                                                                                                                                                                                        // 🔥 CARICA MEMORIA
                                                                                                                                                                                                                                                                                                    const memory = loadMemory()

                                                                                                                                                                                                                                                                                                                // 🔥 SE IL BOT VIENE AGGIUNTO IN UN GRUPPO → IMPOSTA IL CAPO
                                                                                                                                                                                                                                                                                                                            if (msg.message?.protocolMessage?.type === 3 && isGroup) {
                                                                                                                                                                                                                                                                                                                                            const adder = msg.key.participant
                                                                                                                                                                                                                                                                                                                                                            setCapo(from, adder)
                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, "👑 Il capo della griglia è stato impostato!", msg)
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                    // 🔥 RUOLO UTENTE
                                                                                                                                                                                                                                                                                                                                                                                                                const role = getRole(sender, from)

                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔥 COMANDI (solo slash)
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (body.startsWith("/")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const args = body.slice(1).trim().split(/ +/)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const cmd = args.shift().toLowerCase()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // /panel → menu automatico
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (cmd === "panel") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const menu = generateMenu(role, from)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return reply(sock, from, menu, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await handleCommand(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cmd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        args,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                msg,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    askBurgerAI,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sender,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { getRole }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (response) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔥 AI SOLO IN PRIVATO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!isGroup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 🔥 AI SOLO SE TAGGATO NEL GRUPPO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isGroup && body.includes("@393514210321")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            log("error", "Errore nel messaggio: " + err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startBot()
