import makeWASocket, {
            DisconnectReason,
                useMultiFileAuthState
                } from "@whiskeysockets/baileys"

                import { Boom } from "@hapi/boom"
                import { loadMemory, saveMemory, getRole, setCapo } from "./memory.js"
                import { handleCommand } from "./commands.js"
                import { askBurgerAI } from "./ai.js"
                import { isAdmin, isOwner, reply, log } from "./utils.js"
                import qrcode from "qrcode-terminal"
                import express from "express"

                // Variabile per salvare l'ultimo QR generato
                let lastQR = "QR non ancora generato. Attendi che il bot richieda il login."

                // Server Express per mostrare il QR ASCII
                const app = express()

                app.get("/qr", (req, res) => {
                    res.setHeader("Content-Type", "text/plain")
                        res.send(lastQR)
                        })

                        app.listen(3000, () => console.log("Server QR attivo su porta 3000"))

                        async function startBot() {
                            const { state, saveCreds } = await useMultiFileAuthState("./auth")

                                const sock = makeWASocket({
                                        auth: state,
                                                printQRInTerminal: false,
                                                        browser: ["Chrome (Linux)", "Chrome", "1.0"]
                                                            })

                                                                sock.ev.on("creds.update", saveCreds)

                                                                    // 🔥 QR + RICONNESSIONE AUTOMATICA
                                                                        sock.ev.on("connection.update", (update) => {
                                                                                const { connection, lastDisconnect, qr } = update

                                                                                        if (qr) {
                                                                                                    console.log("QR aggiornato! Vai su /qr per vederlo.")

                                                                                                                qrcode.generate(qr, { small: true }, (ascii) => {
                                                                                                                                lastQR = ascii
                                                                                                                                            })
                                                                                                                                                    }

                                                                                                                                                            if (connection === "close") {
                                                                                                                                                                        const shouldReconnect =
                                                                                                                                                                                        lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut
                                                                                                                                                                                                    if (shouldReconnect) startBot()
                                                                                                                                                                                                            }
                                                                                                                                                                                                                })

                                                                                                                                                                                                                    // 🔥 GESTIONE MESSAGGI
                                                                                                                                                                                                                        sock.ev.on("messages.upsert", async ({ messages }) => {
                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                            const msg = messages[0]
                                                                                                                                                                                                                                                        if (!msg.message) return

                                                                                                                                                                                                                                                                    const from = msg.key.remoteJid
                                                                                                                                                                                                                                                                                const isGroup = from.endsWith("@g.us")
                                                                                                                                                                                                                                                                                            const sender = msg.key.participant || msg.key.remoteJid
                                                                                                                                                                                                                                                                                                        const body =
                                                                                                                                                                                                                                                                                                                        msg.message.conversation ||
                                                                                                                                                                                                                                                                                                                                        msg.message.extendedTextMessage?.text ||
                                                                                                                                                                                                                                                                                                                                                        ""

                                                                                                                                                                                                                                                                                                                                                                    log("info", `Messaggio da ${sender}: ${body}`)

                                                                                                                                                                                                                                                                                                                                                                                const memory = loadMemory()

                                                                                                                                                                                                                                                                                                                                                                                            if (msg.message?.protocolMessage?.type === 3 && isGroup) {
                                                                                                                                                                                                                                                                                                                                                                                                            const adder = msg.key.participant
                                                                                                                                                                                                                                                                                                                                                                                                                            setCapo(from, adder)
                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, "👑 Il capo della griglia è stato impostato!", msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const role = getRole(sender, from)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (body.startsWith("/")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const args = body.slice(1).trim().split(/ +/)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const cmd = args.shift().toLowerCase()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (cmd === "panel") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const menu = generateMenu(role, from)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return reply(sock, from, menu, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const response = await handleCommand(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cmd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                args,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        msg,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            askBurgerAI,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sender,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { getRole }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (response) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!isGroup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isGroup && body.includes("@393514210321")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            log("error", "Errore nel messaggio: " + err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startBot()
