import fs from "fs"
import makeWASocket, {
    DisconnectReason,
        useMultiFileAuthState
        } from "@whiskeysockets/baileys"

        import qrcode from "qrcode-terminal"
        import { loadMemory, saveMemory, getRole, setCapo } from "./memory.js"
        import { handleCommand } from "./commands.js"
        import { askBurgerAI } from "./ai.js"
        import { isAdmin, isOwner, reply, log } from "./utils.js"

        // ⭐ CANCELLA AUTOMATICAMENTE LA CARTELLA AUTH
        if (fs.existsSync("./auth")) {
            fs.rmSync("./auth", { recursive: true, force: true })
                console.log("Cartella auth rimossa automaticamente.")
                }

                // Variabile globale per salvare il QR ASCII
                let lastQR = "QR non ancora generato."

                // Funzione per far leggere il QR al server Express
                export function getLastQR() {
                    return lastQR
                    }

                    // Funzione principale del bot
                    export async function startBot() {
                        console.log("Avvio del bot WhatsApp...")

                            const { state, saveCreds } = await useMultiFileAuthState("./auth")

                                const sock = makeWASocket({
                                        auth: state,
                                                printQRInTerminal: true,
                                                        browser: ["Ububtu", "Chrome (Linux)", "Chrome", "2.0.0"]
                                                            })

                                                                sock.ev.on("creds.update", saveCreds)

                                                                    // QR + riconnessione
                                                                        sock.ev.on("connection.update", (update) => {
                                                                                const { connection, lastDisconnect, qr } = update

                                                                                        if (qr) {
                                                                                                    console.log("QR aggiornato! Vai su /qr per vederlo.")

                                                                                                                qrcode.generate(qr, { small: true }, (ascii) => {
                                                                                                                                lastQR = ascii
                                                                                                                                            })
                                                                                                                                                    }

                                                                                                                                                            if (connection === "close") {
                                                                                                                                                                        const statusCode = lastDisconnect?.error?.statusCode
                                                                                                                                                                                    const shouldReconnect = statusCode !== DisconnectReason.loggedOut

                                                                                                                                                                                                if (shouldReconnect) {
                                                                                                                                                                                                                console.log("Connessione chiusa, riconnessione...")
                                                                                                                                                                                                                                startBot()
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                            if (connection === "open") {
                                                                                                                                                                                                                                                                        console.log("Bot connesso a WhatsApp!")
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                    })

                                                                                                                                                                                                                                                                                        // Gestione messaggi
                                                                                                                                                                                                                                                                                            sock.ev.on("messages.upsert", async ({ messages }) => {
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                const msg = messages[0]
                                                                                                                                                                                                                                                                                                                            if (!msg.message) return

                                                                                                                                                                                                                                                                                                                                        const from = msg.key.remoteJid
                                                                                                                                                                                                                                                                                                                                                    const isGroup = from.endsWith("@g.us")
                                                                                                                                                                                                                                                                                                                                                                const sender = msg.key.participant || msg.key.remoteJid
                                                                                                                                                                                                                                                                                                                                                                            const body =
                                                                                                                                                                                                                                                                                                                                                                                            msg.message.conversation ||
                                                                                                                                                                                                                                                                                                                                                                                                            msg.message.extendedTextMessage?.text ||
                                                                                                                                                                                                                                                                                                                                                                                                                            ""

                                                                                                                                                                                                                                                                                                                                                                                                                                        log("info", `Messaggio da ${sender}: ${body}`)

                                                                                                                                                                                                                                                                                                                                                                                                                                                    const memory = loadMemory()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Cambio capo gruppo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (msg.message?.protocolMessage?.type === 3 && isGroup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const adder = msg.key.participant
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setCapo(from, adder)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, "👑 Il capo della griglia è stato impostato!", msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const role = getRole(sender, from)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Comandi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (body.startsWith("/")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const args = body.slice(1).trim().split(/ +/)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const cmd = args.shift().toLowerCase()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (cmd === "panel") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const menu = generateMenu(role, from)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return reply(sock, from, menu, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const response = await handleCommand(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cmd,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            args,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    msg,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        askBurgerAI,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sender,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { getRole }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (response) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Chat privata → AI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!isGroup) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Mention → AI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (isGroup && body.includes("@393514210321")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const response = await askBurgerAI(body, sender)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return reply(sock, from, response, msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                log("error", "Errore nel messaggio: " + err.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }