/**
 *  * 🔥 Parser intelligente per comandi personalizzati
  * Analizza la descrizione e genera una lista di azioni strutturate.
   */
   export function detectActions(description, memory) {
       const text = description.toLowerCase()
           const actions = []

               // ============================
                   // 🔥 1) KICK SINGOLO
                       // ============================
                           if (
                                   text.includes("kick ") ||
                                           text.includes("caccia ") ||
                                                   text.includes("espelli ")
                                                       ) {
                                                               actions.push({
                                                                           type: "kick",
                                                                                       target: "single"
                                                                                               })
                                                                                                   }

                                                                                                       // ============================
                                                                                                           // 🔥 2) KICK ALL
                                                                                                               // ============================
                                                                                                                   if (
                                                                                                                           text.includes("kicka tutti") ||
                                                                                                                                   text.includes("caccia tutti") ||
                                                                                                                                           text.includes("espelli tutti") ||
                                                                                                                                                   text.includes("svuota gruppo")
                                                                                                                                                       ) {
                                                                                                                                                               actions.push({
                                                                                                                                                                           type: "kickall"
                                                                                                                                                                                   })
                                                                                                                                                                                       }

                                                                                                                                                                                           // ============================
                                                                                                                                                                                               // 🔥 3) CLEAR CHAT
                                                                                                                                                                                                   // ============================
                                                                                                                                                                                                       if (
                                                                                                                                                                                                               text.includes("pulisci") ||
                                                                                                                                                                                                                       text.includes("svuota chat") ||
                                                                                                                                                                                                                               text.includes("cancella messaggi")
                                                                                                                                                                                                                                   ) {
                                                                                                                                                                                                                                           actions.push({
                                                                                                                                                                                                                                                       type: "clear"
                                                                                                                                                                                                                                                               })
                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                       // ============================
                                                                                                                                                                                                                                                                           // 🔥 4) RESET FUNZIONI
                                                                                                                                                                                                                                                                               // ============================
                                                                                                                                                                                                                                                                                   if (
                                                                                                                                                                                                                                                                                           text.includes("resetta") ||
                                                                                                                                                                                                                                                                                                   text.includes("azzera") ||
                                                                                                                                                                                                                                                                                                           text.includes("ripristina funzioni")
                                                                                                                                                                                                                                                                                                               ) {
                                                                                                                                                                                                                                                                                                                       actions.push({
                                                                                                                                                                                                                                                                                                                                   type: "resetfunzioni"
                                                                                                                                                                                                                                                                                                                                           })
                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                   // ============================
                                                                                                                                                                                                                                                                                                                                                       // 🔥 5) MESSAGGIO AUTOMATICO
                                                                                                                                                                                                                                                                                                                                                           // ============================
                                                                                                                                                                                                                                                                                                                                                               if (
                                                                                                                                                                                                                                                                                                                                                                       text.includes("manda messaggio") ||
                                                                                                                                                                                                                                                                                                                                                                               text.includes("invia messaggio") ||
                                                                                                                                                                                                                                                                                                                                                                                       text.includes("rispondi con")
                                                                                                                                                                                                                                                                                                                                                                                           ) {
                                                                                                                                                                                                                                                                                                                                                                                                   const match = description.match(/"(.*?)"/)
                                                                                                                                                                                                                                                                                                                                                                                                           actions.push({
                                                                                                                                                                                                                                                                                                                                                                                                                       type: "send",
                                                                                                                                                                                                                                                                                                                                                                                                                                   text: match ? match[1] : null
                                                                                                                                                                                                                                                                                                                                                                                                                                           })
                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                   // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                       // 🔥 6) AGGIUNGI MOD
                                                                                                                                                                                                                                                                                                                                                                                                                                                           // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text.includes("aggiungi mod") ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               text.includes("promuovi mod") ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text.includes("rendi mod")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   actions.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               type: "addmod"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // 🔥 7) RIMUOVI MOD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   text.includes("rimuovi mod") ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           text.includes("togli mod") ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   text.includes("declassa mod")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               actions.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type: "delmod"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // 🔥 8) FALLBACK AI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (actions.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               actions.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type: "ai"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
